services:
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-db:/data/db
    restart: always
    networks:
      - app-network

  backend:
    container_name: backend
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: ./backend
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app-network
    environment:
      MONGODB_URL: mongodb://mongo:27017/task_databse

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    env_file:
      - frontend/.env
    ports:
      - "5173:5173"
    networks:
      - app-network
volumes:
  data-db:
networks:
  app-network:
    driver: bridge
